version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: laravelinertiavue-php
    container_name: laravelinertiavue-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
    networks:
      - laravelinertiavue

  nginx:
    image: nginx:alpine
    container_name: laravelinertiavue-nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravelinertiavue

  db:
    image: mysql:8.0
    container_name: laravelinertiavue-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - laravelinertiavue

networks:
  laravelinertiavue:

volumes:
  db_data:
